// Hand-maintained companion to the generated a2a_pb.bal. NOT generated by
// `bal grpc` -- see a2a/proto/PROVENANCE.md and the gRPC transport binding
// design doc's "Finding 2" / "Known limitation 3" for why this file exists.
//
// Why: `ballerina/grpc`'s ServiceDefinition.getFileDescriptor() resolves a
// root FileDescriptorProto's `dependency` entries ONLY from the descriptor
// map handed to `grpc:Client.initStub`, then calls
// `FileDescriptor.buildFrom(proto, deps, /*allowUnknownDependencies=*/true)`.
// Any dependency missing from that map therefore resolves to a protobuf
// *placeholder* descriptor whose file is named "<Type>.placeholder.proto".
// At (de)serialization time `grpc.Message.getDescriptor()` detects the
// placeholder and re-resolves it by message name through
// `StandardDescriptorBuilder.getFileDescriptorFromMessageName()`, whose table
// covers google.protobuf.{Any,Empty,Timestamp,Duration,Struct} and the nine
// wrappers -- but NOT google.protobuf.Value / ListValue / NullValue. So a
// field typed `google.protobuf.Struct` survives the placeholder round trip
// (which is why `metadata`/`params`/`header` always worked) while
// `Part.data`, typed `google.protobuf.Value`, hit a null FileDescriptor and
// failed with
//   "Failed to frame message: Cannot invoke
//    Descriptors$FileDescriptor.findMessageTypeByName(String) because
//    fileDescriptor is null".
//
// Fix: supply google/protobuf/struct.proto's own FileDescriptorProto in the
// descriptor map so the dependency resolves for real and Value/ListValue/
// NullValue are never placeholders. `grpc.Message` already implements the
// full google.protobuf.Value <-> Ballerina `anydata` mapping (see its
// GOOGLE_PROTOBUF_VALUE_STRUCT_VALUE / GOOGLE_PROTOBUF_VALUE_LIST_VALUE /
// GOOGLE_PROTOBUF_LISTVALUE_VALUES branches) -- that machinery was simply
// unreachable while the descriptor was a placeholder.
//
// Provenance of GOOGLE_PROTOBUF_STRUCT_DESC: the uppercase hex encoding of
// the serialized FileDescriptorProto for google/protobuf/struct.proto, as
// produced by
//   protoc --descriptor_set_out=struct.fds google/protobuf/struct.proto
// (protoc 3.21.7 -- the exact protoc `bal grpc` downloads and uses; the
// struct.proto input is the copy bundled inside grpc-native-1.14.7.jar) and
// then stripping the one-file FileDescriptorSet's leading `0A <varint len>`
// tag. This descriptor is a frozen, versionless protobuf well-known type;
// it does not track the A2A spec and does not need regenerating when
// a2a.proto moves. Verified by a2a/tests/grpc_wire_test.bal.
public const string GOOGLE_PROTOBUF_STRUCT_DESC = "0A1C676F6F676C652F70726F746F6275662F7374727563742E70726F746F120F676F6F676C652E70726F746F6275662298010A06537472756374123B0A066669656C647318012003280B32232E676F6F676C652E70726F746F6275662E5374727563742E4669656C6473456E74727952066669656C64731A510A0B4669656C6473456E74727912100A036B657918012001280952036B6579122C0A0576616C756518022001280B32162E676F6F676C652E70726F746F6275662E56616C7565520576616C75653A02380122B2020A0556616C7565123B0A0A6E756C6C5F76616C756518012001280E321A2E676F6F676C652E70726F746F6275662E4E756C6C56616C7565480052096E756C6C56616C756512230A0C6E756D6265725F76616C75651802200128014800520B6E756D62657256616C756512230A0C737472696E675F76616C75651803200128094800520B737472696E6756616C7565121F0A0A626F6F6C5F76616C756518042001280848005209626F6F6C56616C7565123C0A0C7374727563745F76616C756518052001280B32172E676F6F676C652E70726F746F6275662E5374727563744800520B73747275637456616C7565123B0A0A6C6973745F76616C756518062001280B321A2E676F6F676C652E70726F746F6275662E4C69737456616C7565480052096C69737456616C756542060A046B696E64223B0A094C69737456616C7565122E0A0676616C75657318012003280B32162E676F6F676C652E70726F746F6275662E56616C7565520676616C7565732A1B0A094E756C6C56616C7565120E0A0A4E554C4C5F56414C5545100042550A13636F6D2E676F6F676C652E70726F746F627566420B53747275637450726F746F50015A057479706573F80101A20203475042AA021E476F6F676C652E50726F746F6275662E57656C6C4B6E6F776E5479706573620670726F746F33";

# Dependency descriptors handed to `grpc:Client.initStub` alongside
# `A2A_DESC`, keyed by the exact `dependency` file names declared in
# a2a.proto's FileDescriptorProto.
#
# Only google/protobuf/struct.proto is listed. a2a.proto also depends on
# google/protobuf/empty.proto and google/protobuf/timestamp.proto, but both
# of those ARE covered by `StandardDescriptorBuilder`'s message-name table,
# so their placeholder descriptors are re-resolved correctly and adding them
# here would change working behaviour for no benefit.
public const map<string> A2A_DESCRIPTOR_MAP = {"google/protobuf/struct.proto": GOOGLE_PROTOBUF_STRUCT_DESC};
